---
window:
  padding:
    x: 2
    y: 4
  decorations: none
  startup_mode: Maximized
  dynamic_padding: true

scrolling:
  history: 99999

font:
  normal:
    family: JetBrains Mono
    style: Regular

  bold:
    family: JetBrains Mono
    style: Bold

  italic:
    family: JetBrains Mono
    style: Italic

  size: 11

  offset:
    x: 0
    y: -1

background_opacity: 1

# TokyoNight Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x24283b'
    foreground: '0xc0caf5'

  # Normal colors
  normal:
    black:   '0x1D202F'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xa9b1d6'

  # Bright colors
  bright:
    black:   '0x414868'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xc0caf5'

  indexed_colors:
    - { index: 16, color: '0xff9e64' }
    - { index: 17, color: '0xdb4b4b' }
    
#shell:
#  program: tmux
#  args:
#   - new
#   - -A

key_bindings:
  - { key: F11, mods: None, action: ToggleFullscreen }
#  - { key: Key1, mods: Control, chars: "\x06\x31" }
#  - { key: Key2, mods: Control, chars: "\x06\x32" }
#  - { key: Key3, mods: Control, chars: "\x06\x33" }
#  - { key: Key4, mods: Control, chars: "\x06\x34" }
#  - { key: Key5, mods: Control, chars: "\x06\x35" }
#  - { key: Key6, mods: Control, chars: "\x06\x36" }
#  - { key: Key7, mods: Control, chars: "\x06\x37" }
#  - { key: Key8, mods: Control, chars: "\x06\x38" }
#  - { key: Key9, mods: Control, chars: "\x06\x39" }
#  - { key: Left, mods: Control, chars: "\x06\x48" }
#  - { key: Down, mods: Control, chars: "\x06\x4a" }
