#!/bin/sh

hsetroot -solid "#1a1b26"

xrdb -load $HOME/.Xresources
xset s 180 120
xmodmap $HOME/.Xmodmap
xsetroot -cursor_name left_ptr
setxkbmap

pgrep -x picom > /dev/null || picom -b --config $HOME/.config/picom.conf
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar -r default &

bspc monitor -d ☲ ☳ ☴ ☵ ☷

bspc config border_width         1
bspc config window_gap           4

bspc config active_border_color  "#bb9af7"
bspc config focused_border_color "#565f89"
bspc config normal_border_color  "#414868"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          27

bspc rule -a Fuse state=floating
